services:
    userModel:
        class: Fluency\Silex\Security\Model\UserModel
        ## All parameters are optionals and class must have properly camel case
        ## set method for each parameter
        parameters:
            connection: "db"
            ## Multi-level access
#            connection: "['dbs']['default']"